### ISSUE TITLE
Add support for reading secret values out of environment variables

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa-control-plane#1]
Something like:

```yaml
secrets:
  github:
    username: bob
    password: ${GITHUB_TOKEN}
```
